<?php
/*
 * about.inc
 * 
 * Copyright 2015 Imancha <imancha_266@ymail.com>
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */
 
	echo '<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="page-title">
								<h2>About us</h2>
							</div>
						</div>
					</div>
				</div>
				<div class="row clearfix f-space10"></div>
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="about-company-container">
								<div class="row">
									<div class="col-lg-6 col-md-5 col-sm-12 about-image"><img src="images/aboutus.jpg" alt="about company"></div>
									<div class="col-lg-6 col-md-7 col-sm-12 about-company">
										<h2>IMANCHA<sup>OS</sup></h2>
										<h4>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.</h4>
										<p> Donec rutrum congue leo eget malesuada. Sed porttitor lectus nibh. Curabitur aliquet quam id dui posuere blandit. Curabitur aliquet quam id dui posuere blandit. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Donec sollicitudin molestie malesuada. Sed porttitor lectus nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
										<p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Pellentesque in ipsum id orci porta dapibus. Nulla porttitor accumsan tincidu.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row clearfix f-space30"></div>
				<!-- shop features -->
				<div class="container">
					<div class="row">
						<div class="col-md-3"> 
							<!-- feature box -->
							<div class=" feature-box">
								<div class="feature-title"><i class="fa fa-briefcase circle-icon"></i>
									<h4>Support</h4>
								</div>
								<p> We provide quality <strong>support</strong>, evolve quality outsourcing and professional that strategic theme areas. We synergistically strategize worldwide with functionalities. </p>
							</div>
						</div>
						<!-- end: feature box --> 
						<!-- feature box -->
						<div class="col-md-3">
							<div class=" feature-box">
								<div class="feature-title"><i class="fa fa-star circle-icon"></i>
									<h4>Product Reviews</h4>
								</div>
								<p> A lot of good <strong>product reviews</strong>,  evolve quality outsourcing and professional that strategic theme areas. We synergistically strategize worldwide with functionalities. </p>
							</div>
						</div>
						<!-- end: feature box --> 
						<!-- feature box -->
						
						<div class="col-md-3">
							<div class=" feature-box">
								<div class="feature-title"><i class="fa fa-user circle-icon"></i>
									<h4>Guest Checkout</h4>
								</div>
								<p> You can checkout without,  evolve quality outsourcing and professional that strategic theme areas. We synergistically strategize worldwide with functionalities. </p>
							</div>
						</div>
						<!-- end: feature box --> 
						<!-- feature box -->
						<div class="col-md-3">
							<div class=" feature-box">
								<div class="feature-title"><i class="fa fa-rocket circle-icon"></i>
									<h4>Fast Delivery</h4>
								</div>
								<p> We deliver very fast,  evolve quality <em>outsourcing and professional</em> that strategic theme areas. We synergistically strategize worldwide with functionalities. </p>
							</div>
						</div>
					</div>
				</div>
				<!-- end: shop features -->				
				<div class="row clearfix f-space30"></div>';
?>
